
server:
  port: 8761

spring:
  application:
    name: ead-service-registry

ead:
  serviceRegistry:
    username: adm
    password: adm

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

config-connection with passsword and user
